# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/

# For VietNamese
language: vi
pipeline:
  - name: "SpacyNLP"
    model: "model-final_old"
    case_sensitive: false
  - name: "SpacyTokenizer"
  - name: "CountVectorsFeaturizer"  #bag-of-word
  - name: "EmbeddingIntentClassifier"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: FallbackPolicy
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy

